# Github action to build Jekyll site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Sphinx Preview Build

on:
  push:
    branches: [ master ]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages
  FPM_INDEX: "https://raw.githubusercontent.com/fortran-lang/fpm-registry/HEAD/index.json"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    # Download latest fpm-registry index
    - name: Download fpm-registry index
      run: |
        wget ${{env.FPM_INDEX}} -O ${{env.SRC_DIR}}/_data/fpm_registry_index.json
        
    - name: Checkout page source
      run: git clone https://github.com/henilp105/fortran-lang.org.git
      
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install sphinx
      run: pip3 install --user -r requirements.txt
      
    - name: Build page
      run: make html
      
    - run: touch build/html/.nojekyll

    - name: Deploy documentation sphinx
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.event_name == 'push' && github.repository == 'henilp105/fortran-lang.org' && github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages/pr
        FOLDER: build/html
        CLEAN: false
