# Github action to build Jekyll site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Jekyll Build

on:
  push:
    branches: [ master ]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages
  FPM_INDEX: "https://raw.githubusercontent.com/fortran-lang/fpm-registry/HEAD/index.json"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    # Checkout default branch into SRC_DIR
    - name: Checkout default branch
      uses: actions/checkout@v2
      # with:
      #   path: ${{env.SRC_DIR}}

    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ${{env.PUBLISH_DIR}}
        ref: 'gh-pages'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install ruby 2.7.x
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    # Setup Jekyll in SRC_DIR
    - name: Setup Jekyll
      run: |
        cd ${{env.SRC_DIR}}
        sudo gem install bundler
        bundle config path .bundle
        bundle install
    
    # Download latest fpm-registry index
    - name: Download fpm-registry index
      run: |
        wget ${{env.FPM_INDEX}} -O ${{env.SRC_DIR}}/_data/fpm_registry_index.json

    # Run Jekyll build and copy output to PUBLISH_DIR
    # - name: Build Jekyll Site
    #   run: |
    #     cd ${{env.SRC_DIR}}
    #     bundle exec jekyll build 
    #     cp -r _site/* ../${{env.PUBLISH_DIR}}/
    #     touch ../${{env.PUBLISH_DIR}}/.nojekyll
    
    
    # Add redirects to new webpage
    - name: Redirect to new web page
      run: |
        pip install pyyaml
        python3 redirect.py
        cp -r _site/* ${{env.PUBLISH_DIR}}/
        touch ${{env.PUBLISH_DIR}}/.nojekyll

    # Commit and push changes to remote/gh-pages
    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@v4.4.0
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "Jekyll build, commit ${{github.sha}} (on:push)"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
