name: Build

on: [push, pull_request]

env:
  PUBLISH_DIR: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout page source
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install sphinx
      run: pip3 install --user -r requirements.txt
      
    - name: Build page
      run: make html
      
    - run: touch build/html/.nojekyll

    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@v4.4.0
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "sphinx build, commit ${{github.sha}} (on:push)"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
